version: '3.7'

services:
  pdatabase:
    image: postgis/postgis:13-3.3
    environment:
      - POSTGRES_USER=user1
      - POSTGRES_PASSWORD=1
      - POSTGRES_DB=pdb
    volumes:
      - pg_data:/var/lib/postgresql/data

  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:1111"
    ports:
      - 1111:1111
    links:
      - pdatabase:pdatabase
    volumes:
      - .:/code
    environment:
      - POSTGRES_USER=user1
      - POSTGRES_PASSWORD=1
      - POSTGRES_DB=pdb
    depends_on:
      - pdatabase

networks:
  djangonetwork:
    driver: bridge

volumes:
  pg_data: