# Generated by Django 4.2.3 on 2023-08-14 07:44

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_locator', '0002_canton_contour_district_region_delete_bank_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestContour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
    ]
