# Generated by Django 4.2.3 on 2023-08-18 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_locator', '0004_alter_canton_geometry_alter_district_geometry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestForShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=123)),
            ],
        ),
    ]
