# Generated by Django 4.2.3 on 2023-08-18 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map_locator', '0005_testforshow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestForShow',
        ),
    ]
